#pragma once

enum	OBJID	{ OBJ_PLAYER, OBJ_MONSTER, OBJ_Ball	,OBJ_END};	// abstract factory

enum	DIRECTION {DIR_LEFT, DIR_RIGHT, DIR_UP, DIR_DOWN, DIR_LU, DIR_LD, DIR_RU, DIR_RD};

enum    COLLISIONTARGET {CTARGET_TOP, CTARGET_BOTTOM, CTARGET_LEFT, CTARGET_RIGHT };